### ISSUE TITLE
How to add styling for elements

### ISSUE THREAD

**Issue by DenisBik** [tfry-git/EmbAJAX#12]
Hello! I am working on a project, web controlled led thing. I dont really want to learn html and Java, so your library EMBAjax is really cool thing for this purpose. But I still want to add some more design to controls using CSS. Can you give me a good example how to do it? How to implement CSS into EMBAjax. As I understood I can get a CSS code for styling a button but where to put it in library functions? There for example? 
MAKE_EmbAJAXPage(page, "EmbAJAX example - Blink","", new EmbAJAXStatic("<h1>Control the builtin LED</h1><p>Set the LED to: "), &mode, new EmbAJAXStatic("</p><p>Blink frequency: <i>SLOW</i>"), &blinkfreq, new EmbAJAXStatic("<i>FAST</i></p>") )
Can you give me some simple example how to add css styling to button or any other controls?

**Comment by tfry-git** [comment]
Hi!

This really still needs documenting / an example, and probably some convenience macros. I hope I'll get around to this, soon. Meanwhile, here's my answer to essentially the same question asked earlier:
https://github.com/tfry-git/EmbAJAX/issues/4#issuecomment-481132734

If you need any further help in getting this to work, just let me know.

**Comment by DenisBik** [comment]
Thank you for a fast response. 
The problem is, I tryed to methods from you previous answer and it didn't workout for me. Probably because I am doing something worng. 
As I understood there are many wasy to change style. First you mentioned "Add a CSS spec to the entire page". I tryed to put this part ""<style>button {color: red;}</style>" after I name my page, but nothing happaned. I tryed adding html and other css code, but in the first case, another styled button was added that wasnt doing anything. in other case whole pagw was blank. 
I understood how to add static elements, but as you mentioned, this option is really strange:) 
And as for the other options you mentioned, I didnt understand hot to implement it at all. Maybe you can give me a better example how to do it? 
If not, I will try to learn html and Java myself, I guess :)

**Comment by tfry-git** [comment]
Alright, I have just added a fresh example for styling. It's nothing pretty, but simply demonstrates the options for appling CSS styling to elements (buttons in this case). So do a git pull, and try that example. Then see, if you can work your way from there. Let me know how it goes.

**Comment by DenisBik** [comment]
Hello again! I was playing with the code for the last 2 days, but it still a little hard to undertand for me to be honest. I was trying to read library API, but it's kinda hard dor me personally. I was trying to make really simple code like in this example https://www.instructables.com/id/Easy-ESP8266-Arduino-Core-Web-Controls-With-EmbAJA/
For example i wanted to have buttons, checkboxes and slider. ALso style all of them a little bit. And make them do something really simeple like make led turn on and off or something and change LED brightness using slider. But it's kinda frustrating. Thank you for buttons style example, it was really useful. But I think that everyone will appreciate example like this, from which I could understand how to simple style different elements and use information from them like simple "if reads that from radio-button -> turn LED on." etc. I think if will be reallu useful for this library and for all th people using it! Tan you for your help, really appreciate it! :)

**Comment by tfry-git** [comment]
Hi! I am trying to provide simple examples to make using EmbAJAX as easy as possible. So if I'm not quite there, I'm all ears. However, I am having some difficulty to understand, what exactly you would like to see / where exactly your difficulty lies.

1) Can you achieve a functional example, without the styling? I.e. is the problem simply how to apply styling to some of the elements? If so, consider posting the code you have, and/or asking more specific questions, so I can get an idea, what you are trying to do, and where exactly the problem is.

2) Or are you trying to turn the "Styling" example into a functional example? That is going to be a little harder, indeed. Try looking and the "Blink" and "Inputs" examples, first. Adapt them to your needs, and worry about the styling later -> see 1), above.

**Comment by DenisBik** [comment]
Well, both are the problems) 
Forst I dont really understand how to make a "reaction function" on pushing buttons or using slider or something. I have seen a "blink" exmaple. There, it's kinda clear how to process button presses. But how to style them- not. 
In all the other situation it's unclear how to process buttons pushing, or, for exmaple, checkboxes etc. 
Also it's unclear how to refer to, for exmaple, radio-buttons, for styling. 
In styling exmaple u showed how to style buttons and <div>, but how to style radio-buttons, slyder etc? It's really confusing for me, maybe it's only my problem ) 
But still in styling exmaple you refer to buttons as #my_button2 or just "button", bot how to refer to radio-buttons. Is it radio? All CSS exmaple call radio-buttons as "radio", but it doesn't work for me. 
I mean, Maybe it's just me, but I think library a bit unclear to use, no offense or something, it's still really cool) 
I will try to play with it more for usre)

**Comment by tfry-git** [comment]
Hi again!

Ok, so two problems. Let's deal with them separately (and as a general piece of programming advice: While it is a good idea to have a *rough* idea of all steps of your programming project ahead of time, you really should worry about implementing and testing the steps one by one):
1) For the most part you do not even need a reaction function. Because keeping track of the state of the controls is one important thing that the library will just do for you. For instance, if you have created a checkbox ```my_checkbox```, you can very simply read its state as ```my_checkbox->isChecked()```. (Note that this is a very fast local operation that you can safely put into your main loop, just like a ```digitalRead()```. The actual network communication has been handled behind the scenes.) Similarly, for a slider, you read the current value as ```my_slider.intValue()```. Please take an in-depth look at the "Inputs" example, and in particular the function ```updateUI()```. It may not look like much, but each control's value is actually read on the server, and written back to the corresponding display on the client. So this example really has all the functions you will need (and more).

1b) The exception really is push buttons, since for these you do not want to read a state, but and event (the click). For this purpose, the EmbAJAXPushbutton constructor takes a custom function as its third parameter. This will be called on each press. Again, see "Inputs" example for an example of how it is done.

1c) You *can*, *optionally* provide a function to be notified on any control change, which can be used to allow the UI to respond faster. This is not *needed* for the basics to work, however. So remember to take one step at a time.

2) For styling by id, you will need to refer to the ```id``` parameter that you have assigned to your EmbAJAXElements as the first parameter to their constructor. It doesn't matter whether you call that ```my_checkbox``` or ```silly_control```, you just need to use the same id in your CSS definition. If in any doubt, it definitely helps to look at the page source in your browser.

2b) Styling checkboxes and radio controls via CSS really isn't so trivial. I'll include an example for that, when I can find the time.

**Comment by tfry-git** [comment]
Alright. You will now find more examples (in particular for styling checkboxes and radio buttons) after a ```git pull```.

Do note that CSS-styling is a science of its own, and I won't be able to talk you through that. But I hope you will find your way to the basics from here. Again, I recommend to focus on the functionality, first, and the styling later.

**Comment by DenisBik** [comment]
Thnak youuuuu very much for help! I will try my best with new exmaples )
