### ISSUE TITLE
automatic update of measured values

### ISSUE THREAD

**Issue by siegmar** [tfry-git/EmbAJAX#35]
First of all I would like to thank you for the great lib.
I would like to display measured values from the Arduino program directly on the web browser and update them cyclically.
The examples always require a request from the browser.
Is this possible with the lib directly ? 
Have a nice day
With best regards
Siegmar

**Comment by tfry-git** [comment]
This is possible, the most straight-forward class for this being purpose EmbAJAXMutableSpan. Simply call setValue() on that, and the updated value will be transmitted to the web browser, automatically.

It is true that, internally, EmbAJAX relies on requests originating from the client browser. However, the page is set up so that the client poll for updates at least once per second (and EmbAJAX will then transmit any changes that have happened, meanwhile). This interval is a trade-off between saving resources (importantly, by avoiding persistent connections) and swift feedback. Should you wish to change the timeout, search for ```setInterval(doPoll,1000);``` inside EmbAJAX.cpp.

**Comment by siegmar** [comment]
Thank you sooooo much for your quick  reply.
I will test it .

**Comment by tfry-git** [comment]
To clarify: You can call XY.setValue() anywhere, not just inside updateUI(). The latter allows to provide an immediate reaction to a UI event, without waiting for the next poll.

(Thinking about it, right now, I notice that it may be confusing that updateUI() is in fact _not_ called for the regular polls. I may need to do some more thinking on that, and certainly add an example one way or the other.)

**Comment by siegmar** [comment]
It is working well !!
Thanks for your help and have a nice day
cheers
Siegmar
