### ISSUE TITLE
Can we make website responsive??

### ISSUE THREAD

**Issue by DevSwift** [tfry-git/EmbAJAX#5]
I am trying to figure out how to make website responsive, Can you help me?

<meta name="viewport" content="width=device-width, initial-scale=1.0">

EDIT:

I found solution thanks to @No3x https://github.com/No3x/esp8266-grill

**Comment by No3x** [comment]
I guess you refer to [EmbAJAXExtensions.cpp#L19-L31](https://github.com/No3x/esp8266-grill/blob/9110fe3/lib/EmbAJAXExtensions/EmbAJAXExtensions.cpp#L19-L31) in particular.
It adds the viewport size via JS, because it was the easiest way to add the header this way.
Btw. it should be `width=device-width` instead of `width=320`.

**Comment by tfry-git** [comment]
You can also use the header_add-parameter to EmbAJAXPage() for this. E.g.:

```MAKE_EmbAJAXPage(page, "MyTitle", "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">", ...)```

I guess I should add an example (and possibly some convenience macros) for this.
