### ISSUE TITLE
Is it possible to select a different page based on data processing

### ISSUE THREAD

**Issue by eporocrail** [tfry-git/EmbAJAX#8]
What I am looking for is:

The user makes a selection. This selection leads to some dataprocessing and the need to use one out of three pages.

What I do now is presenting the outcome of the dataprocessing on the displayed page and have the user click on a link to goto the right page.

It would be better to present the desired page right away without having the user clicking a link.

**Comment by tfry-git** [comment]
If I understand you correctly: You have something like
- a radio-control on top
- depending on the selection in the radio-control, the lower part of the page will be vastly different
- you want that lower part to change, immediately, when making a selection in the radio-control, without any further clicks

If this is your scenario, I suggest the following setup
* EmbAJAXPage containing
  * Radio-Control
  * EmbAJAXHideableContainer subpage1
    * [containing whatever]
  * EmbAJAXHideableContainer subpage2
    * [containing whatever else]

Logically, everything would be on a single page, but you'd call ```subpage1/2.setVisible(true/false);```, according to the selection in the radio-control.

If you'd rather have a more wizard-like interface (user makes selection, may be presented with feedback, then clicks "Ok" to proceed to the next step), then I think your current approach is the way to go. However, you can polish it a bit by:
- Instead of your current links, create separate *hideable* buttons like this:
```
EmbAJAXHideableContainer hideable_link_a (new EmbAJAXStatic("<button onclick=\"window.location.href='/page_a'\">Proceed (to page A)</button>"));
EmbAJAXHideableContainer hideable_link_b (EmbAJAXStatic("<button onclick=\"window.location.href='/page_b'\">Proceed (to page B)</button>"));
```

Then while doing your processing, show / hide the separate buttons as appropriate so that the user will only see one.
